/**
 *
 * $Id$
 */
package resourcePetriNet.validation;

import org.eclipse.emf.common.util.EList;

import resourcePetriNet.GenericPlace;
import resourcePetriNet.Transition;

/**
 * A sample validator interface for {@link resourcePetriNet.OutputArc}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OutputArcValidator {
	boolean validate();

	boolean validateOutputArcFromTransition(Transition value);
	boolean validateOutputArcToPlace(GenericPlace value);
	boolean validateWeight(EList<Integer> value);
}
