/**
 *
 * $Id$
 */
package resourcePetriNet.validation;

import org.eclipse.emf.common.util.EList;

import resourcePetriNet.GenericPlace;
import resourcePetriNet.InputArc;
import resourcePetriNet.OutputArc;
import resourcePetriNet.Transition;

/**
 * A sample validator interface for {@link resourcePetriNet.PetriNet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PetriNetValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateContainsGenericPlaces(EList<GenericPlace> value);
	boolean validateContainsTransitions(EList<Transition> value);
	boolean validateContainsInputArcs(EList<InputArc> value);
	boolean validateContainsOutputArcs(EList<OutputArc> value);
}
